<?php

/**
 * @file
 * Contains pagedesigner_effects.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pagedesigner_effects_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the pagedesigner_effects module.
        case 'help.page.pagedesigner_effects':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Pagedesigner effects extension') . '</p>';
            return $output;

        default:
    }
}

function pagedesigner_effects_page_attachments(array &$page)
{
    $page['#attached']['library'][] = 'pagedesigner_effects/frontend';
}
